- name: "Since Helm charts that we are going to use still However, we will be installing Helm v2.16.7"
  shell: |
      curl -s https://storage.googleapis.com/kubernetes-helm/helm-v2.16.7-linux-amd64.tar.gz | tar xz
      cd linux-amd64
      sudo mv helm /bin
  become: yes
  become_user: vagrant 

- name: "Create tiller service accoun and grant cluster admin to the tiller service account"
  shell: |
      kubectl -n kube-system create serviceaccount tiller
      kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  become: yes
  become_user: vagrant 

- name: "No security, ideal for running in a sandbox environment."
  shell: |
        helm init --service-account tiller
  become: yes
  become_user: vagrant 